import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./component/Nav";
import Footer from "./component/Footer";
import NavTop from "./component/NavTop";
import { Outfit } from "next/font/google"
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="px-12.5 pt-4.5  max-[640px]:px-1.25 bg-Orange-97">
        <NavTop/>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
